# -*- coding: utf-8 -*-
"""adultincome.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6GOqNTNv8GR4-2kkB4OJpf49sITvS7R
"""

# ============================================================
# ADULT INCOME - FEATURE ENGINEERING AND EDA PROJECT
# ============================================================

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# 1. LOAD DATASET
# ============================================================

# If you have the CSV file, upload it
from google.colab import files

uploaded = files.upload()

filename = next(iter(uploaded))
df = pd.read_csv(filename)

print("Dataset loaded successfully!")
print("\nFirst 5 rows:")
print(df.head())

# ============================================================
# 2. BASIC INFORMATION
# ============================================================

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
print(df.info())

# ============================================================
# 3. CHECK MISSING VALUES
# ============================================================

print("\nMissing Values:")
print(df.isnull().sum())

# Remove missing values
df = df.dropna()

print("\nShape after removing missing values:")
print(df.shape)

# ============================================================
# 4. FEATURE ENGINEERING
# ============================================================

# Create Age Group
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 25, 40, 60, 100],
    labels=["Young", "Adult", "Middle_Age", "Senior"]
)

# Create Net Capital
df["net_capital"] = (
    df["capital_gain"] - df["capital_loss"]
)

# Create Work Hours Category
df["work_hours_category"] = pd.cut(
    df["hours_per_week"],
    bins=[0, 30, 40, 100],
    labels=["Part_Time", "Full_Time", "Over_Time"]
)

# Create Education Level
df["education_level"] = pd.cut(
    df["education_num"],
    bins=[0, 8, 12, 16],
    labels=["Low", "Medium", "High"]
)

print("\nFeature Engineering Completed!")

print("\nNew Features:")
print(df[
    [
        "age",
        "age_group",
        "net_capital",
        "hours_per_week",
        "work_hours_category",
        "education_num",
        "education_level"
    ]
].head())

# ============================================================
# 5. EXPLORATORY DATA ANALYSIS
# ============================================================

# -----------------------------
# Income Distribution
# -----------------------------

plt.figure(figsize=(7, 5))

sns.countplot(
    x="income",
    data=df
)

plt.title("Income Distribution")
plt.xlabel("Income")
plt.ylabel("Count")
plt.show()


# -----------------------------
# Income vs Education
# -----------------------------

plt.figure(figsize=(12, 6))

sns.countplot(
    x="education",
    hue="income",
    data=df
)

plt.xticks(rotation=45)
plt.title("Income by Education")
plt.xlabel("Education")
plt.ylabel("Count")
plt.show()


# -----------------------------
# Age vs Income
# -----------------------------

plt.figure(figsize=(7, 5))

sns.boxplot(
    x="income",
    y="age",
    data=df
)

plt.title("Age vs Income")
plt.xlabel("Income")
plt.ylabel("Age")
plt.show()


# -----------------------------
# Hours Worked vs Income
# -----------------------------

plt.figure(figsize=(7, 5))

sns.boxplot(
    x="income",
    y="hours_per_week",
    data=df
)

plt.title("Working Hours vs Income")
plt.xlabel("Income")
plt.ylabel("Hours per Week")
plt.show()


# -----------------------------
# Income by Gender
# -----------------------------

plt.figure(figsize=(7, 5))

sns.countplot(
    x="sex",
    hue="income",
    data=df
)

plt.title("Income by Gender")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()


# -----------------------------
# Income by Age Group
# -----------------------------

plt.figure(figsize=(8, 5))

sns.countplot(
    x="age_group",
    hue="income",
    data=df
)

plt.title("Income by Age Group")
plt.xlabel("Age Group")
plt.ylabel("Count")
plt.show()


# -----------------------------
# Income by Work Hours
# -----------------------------

plt.figure(figsize=(8, 5))

sns.countplot(
    x="work_hours_category",
    hue="income",
    data=df
)

plt.title("Income by Work Hours Category")
plt.xlabel("Work Hours Category")
plt.ylabel("Count")
plt.show()


# ============================================================
# 6. CORRELATION MATRIX
# ============================================================

numeric_columns = df.select_dtypes(
    include=np.number
).columns

plt.figure(figsize=(10, 7))

sns.heatmap(
    df[numeric_columns].corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Matrix")
plt.show()


# ============================================================
# 7. DISPLAY FINAL DATASET
# ============================================================

print("\nFinal Dataset:")
print(df.head(10))

print("\nFinal Dataset Shape:")
print(df.shape)

print("\nFinal Dataset Columns:")
print(df.columns.tolist())


# ============================================================
# 8. SAVE CLEANED DATASET
# ============================================================

df.to_csv(
    "adult_income_cleaned.csv",
    index=False
)

print("\nCleaned dataset saved as:")
print("adult_income_cleaned.csv")


# ============================================================
# 9. DOWNLOAD CLEANED DATASET
# ============================================================

files.download("adult_income_cleaned.csv")