# -*- coding: utf-8 -*-
"""AUTOMPG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZD08e0gXgR0aWibni6yYTAOotffXsSD
"""

# ============================================================
# AUTO MPG - LINEAR REGRESSION, FEATURE SCALING AND ENCODING
# ============================================================

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


# ============================================================
# 1. LOAD DATASET
# ============================================================

uploaded = files.upload()

filename = next(iter(uploaded))

df = pd.read_csv(filename)

# Handle 'horsepower' column with '?' values
df['horsepower'] = df['horsepower'].replace('?', np.nan)
df['horsepower'] = pd.to_numeric(df['horsepower'])

print("Dataset loaded successfully!")

print("\nFirst 5 rows:")
print(df.head())


# ============================================================
# 2. BASIC INFORMATION
# ============================================================

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nStatistical Summary:")
print(df.describe())


# ============================================================
# 3. HANDLE MISSING VALUES
# ============================================================

df = df.dropna()

print("\nShape after removing missing values:")
print(df.shape)


# ============================================================
# 4. EXPLORATORY DATA ANALYSIS
# ============================================================

# MPG distribution

plt.figure(figsize=(8, 5))

sns.histplot(
    df["mpg"],
    bins=30,
    kde=True
)

plt.title("MPG Distribution")
plt.xlabel("Miles Per Gallon")
plt.ylabel("Frequency")

plt.show()


# Horsepower vs MPG

plt.figure(figsize=(8, 5))

sns.scatterplot(
    x="horsepower",
    y="mpg",
    data=df
)

plt.title("Horsepower vs MPG")
plt.xlabel("Horsepower")
plt.ylabel("MPG")

plt.show()


# Weight vs MPG

plt.figure(figsize=(8, 5))

sns.scatterplot(
    x="weight",
    y="mpg",
    data=df
)

plt.title("Weight vs MPG")
plt.xlabel("Weight")
plt.ylabel("MPG")

plt.show()


# ============================================================
# 5. DEFINE FEATURES AND TARGET
# ============================================================

X = df[
    [
        "cylinders",
        "displacement",
        "horsepower",
        "weight",
        "acceleration",
        "model_year",
        "origin"
    ]
]

y = df["mpg"]

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget:")
print("mpg")


# ============================================================
# 6. DEFINE NUMERICAL AND CATEGORICAL FEATURES
# ============================================================

numeric_features = [
    "cylinders",
    "displacement",
    "horsepower",
    "weight",
    "acceleration",
    "model_year"
]

categorical_features = [
    "origin"
]


# ============================================================
# 7. PREPROCESSING
# ============================================================

numeric_pipeline = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="median")
    ),
    (
        "scaler",
        StandardScaler()
    )
])

categorical_pipeline = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "encoder",
        OneHotEncoder(
            handle_unknown="ignore"
        )
    )
])


# ============================================================
# 8. COMBINE PREPROCESSING
# ============================================================

preprocessor = ColumnTransformer([
    (
        "numeric",
        numeric_pipeline,
        numeric_features
    ),
    (
        "categorical",
        categorical_pipeline,
        categorical_features
    )
])


# ============================================================
# 9. CREATE LINEAR REGRESSION PIPELINE
# ============================================================

model = Pipeline([
    (
        "preprocessor",
        preprocessor
    ),
    (
        "regressor",
        LinearRegression()
    )
])


# ============================================================
# 10. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)


# ============================================================
# 11. TRAIN MODEL
# ============================================================

model.fit(
    X_train,
    y_train
)

print("\nLinear Regression Model Trained Successfully!")


# ============================================================
# 12. MAKE PREDICTIONS
# ============================================================

y_pred = model.predict(
    X_test
)


# ============================================================
# 13. MODEL EVALUATION
# ============================================================

mse = mean_squared_error(
    y_test,
    y_pred
)

rmse = np.sqrt(mse)

r2 = r2_score(
    y_test,
    y_pred
)

print("\n==============================")
print("MODEL PERFORMANCE")
print("==============================")

print("MSE:", mse)

print("RMSE:", rmse)

print("R2 Score:", r2)


# ============================================================
# 14. ACTUAL VS PREDICTED
# ============================================================

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    y_pred,
    alpha=0.6
)

plt.xlabel("Actual MPG")
plt.ylabel("Predicted MPG")

plt.title(
    "Actual vs Predicted MPG"
)

plt.show()


# ============================================================
# 15. RESIDUAL PLOT
# ============================================================

residuals = y_test - y_pred

plt.figure(figsize=(8, 5))

plt.scatter(
    y_pred,
    residuals,
    alpha=0.6
)

plt.axhline(
    y=0,
    linestyle="--"
)

plt.xlabel("Predicted MPG")
plt.ylabel("Residuals")

plt.title("Residual Plot")

plt.show()


# ============================================================
# 16. ACTUAL VS PREDICTED TABLE
# ============================================================

comparison = pd.DataFrame({
    "Actual MPG": y_test.values,
    "Predicted MPG": y_pred
})

print("\n==============================")
print("ACTUAL VS PREDICTED")
print("==============================")

print(comparison.head(20))


# ============================================================
# 17. FINAL RESULT
# ============================================================

print("\n======================================")
print("AUTO MPG PROJECT COMPLETED")
print("======================================")

print("\nMean Squared Error:")
print(mse)

print("\nRoot Mean Squared Error:")
print(rmse)

print("\nR2 Score:")
print(r2)