# -*- coding: utf-8 -*-
"""california housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bB0YLdNLH512OL3d3gZxU8esVtLtTCRe
"""

# ============================================================
# CALIFORNIA HOUSING - LINEAR REGRESSION AND REGULARISATION
# ============================================================

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score


# ============================================================
# 1. LOAD CSV DATASET
# ============================================================

uploaded = files.upload()

filename = next(iter(uploaded))

df = pd.read_csv(filename)

print("Dataset loaded successfully!")

print("\nFirst 5 rows:")
print(df.head())


# ============================================================
# 2. BASIC INFORMATION
# ============================================================

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nStatistical Summary:")
print(df.describe())


# ============================================================
# 3. HANDLE MISSING VALUES
# ============================================================

df = df.dropna()

print("\nShape after removing missing values:")
print(df.shape)


# ============================================================
# 4. EXPLORATORY DATA ANALYSIS
# ============================================================

# Target distribution

plt.figure(figsize=(8, 5))

sns.histplot(
    df["MedHouseVal"],
    bins=30,
    kde=True
)

plt.title("Distribution of House Values")
plt.xlabel("Median House Value")
plt.ylabel("Frequency")

plt.show()


# Feature distributions

df.hist(
    figsize=(12, 10),
    bins=30
)

plt.suptitle("Feature Distributions")

plt.show()


# Correlation matrix

plt.figure(figsize=(10, 8))

sns.heatmap(
    df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Matrix")

plt.show()


# ============================================================
# 5. DEFINE FEATURES AND TARGET
# ============================================================

X = df.drop(
    "MedHouseVal",
    axis=1
)

y = df["MedHouseVal"]

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget:")
print("MedHouseVal")


# ============================================================
# 6. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)


# ============================================================
# 7. FEATURE SCALING
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)

print("\nFeature Scaling Completed!")


# ============================================================
# 8. LINEAR REGRESSION
# ============================================================

linear_model = LinearRegression()

linear_model.fit(
    X_train_scaled,
    y_train
)

linear_pred = linear_model.predict(
    X_test_scaled
)

linear_mse = mean_squared_error(
    y_test,
    linear_pred
)

linear_rmse = np.sqrt(
    linear_mse
)

linear_r2 = r2_score(
    y_test,
    linear_pred
)

print("\n==============================")
print("LINEAR REGRESSION")
print("==============================")

print("MSE:", linear_mse)
print("RMSE:", linear_rmse)
print("R2 Score:", linear_r2)


# ============================================================
# 9. RIDGE REGRESSION
# ============================================================

ridge_model = Ridge(
    alpha=1.0
)

ridge_model.fit(
    X_train_scaled,
    y_train
)

ridge_pred = ridge_model.predict(
    X_test_scaled
)

ridge_mse = mean_squared_error(
    y_test,
    ridge_pred
)

ridge_rmse = np.sqrt(
    ridge_mse
)

ridge_r2 = r2_score(
    y_test,
    ridge_pred
)

print("\n==============================")
print("RIDGE REGRESSION")
print("==============================")

print("MSE:", ridge_mse)
print("RMSE:", ridge_rmse)
print("R2 Score:", ridge_r2)


# ============================================================
# 10. LASSO REGRESSION
# ============================================================

lasso_model = Lasso(
    alpha=0.01,
    max_iter=10000
)

lasso_model.fit(
    X_train_scaled,
    y_train
)

lasso_pred = lasso_model.predict(
    X_test_scaled
)

lasso_mse = mean_squared_error(
    y_test,
    lasso_pred
)

lasso_rmse = np.sqrt(
    lasso_mse
)

lasso_r2 = r2_score(
    y_test,
    lasso_pred
)

print("\n==============================")
print("LASSO REGRESSION")
print("==============================")

print("MSE:", lasso_mse)
print("RMSE:", lasso_rmse)
print("R2 Score:", lasso_r2)


# ============================================================
# 11. MODEL COMPARISON
# ============================================================

results = pd.DataFrame({

    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Lasso Regression"
    ],

    "MSE": [
        linear_mse,
        ridge_mse,
        lasso_mse
    ],

    "RMSE": [
        linear_rmse,
        ridge_rmse,
        lasso_rmse
    ],

    "R2 Score": [
        linear_r2,
        ridge_r2,
        lasso_r2
    ]
})

print("\n==============================")
print("MODEL COMPARISON")
print("==============================")

print(results)


# ============================================================
# 12. ACTUAL VS PREDICTED VALUES
# ============================================================

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    linear_pred,
    alpha=0.5
)

plt.xlabel("Actual House Value")
plt.ylabel("Predicted House Value")

plt.title(
    "Actual vs Predicted - Linear Regression"
)

plt.show()


# ============================================================
# 13. MODEL COEFFICIENTS
# ============================================================

coefficients = pd.DataFrame({

    "Feature": X.columns,

    "Linear Regression": linear_model.coef_,

    "Ridge Regression": ridge_model.coef_,

    "Lasso Regression": lasso_model.coef_

})

print("\n==============================")
print("MODEL COEFFICIENTS")
print("==============================")

print(coefficients)


# ============================================================
# 14. COEFFICIENT VISUALIZATION
# ============================================================

coefficients.set_index(
    "Feature"
).plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title(
    "Linear, Ridge and Lasso Coefficients"
)

plt.xlabel("Features")
plt.ylabel("Coefficient")

plt.xticks(rotation=45)

plt.show()


# ============================================================
# 15. FIND BEST MODEL
# ============================================================

best_model = results.loc[
    results["R2 Score"].idxmax(),
    "Model"
]

best_score = results["R2 Score"].max()

print("\n======================================")
print("CALIFORNIA HOUSING PROJECT COMPLETED")
print("======================================")

print("\nBest Model:")
print(best_model)

print("\nBest R2 Score:")
print(best_score)


# ============================================================
# 16. SAVE CLEANED DATASET
# ============================================================

df.to_csv(
    "california_housing_cleaned.csv",
    index=False
)

print("\nCleaned dataset saved successfully!")

# Download cleaned CSV
files.download(
    "california_housing_cleaned.csv"
)