# -*- coding: utf-8 -*-
"""Diabeties.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fa3L0_KccFdPPOnmeTVP0UjaBENFCDCO
"""

# ============================================================
# DIABETES SEVERITY - MULTINOMIAL LOGISTIC REGRESSION
# ============================================================

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

# ============================================================
# 1. LOAD DATASET
# ============================================================

uploaded = files.upload()

filename = next(iter(uploaded))

df = pd.read_csv(filename)

print("Dataset loaded successfully!")

print("\nFirst 5 rows:")
print(df.head())


# ============================================================
# 2. BASIC INFORMATION
# ============================================================

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())


# ============================================================
# 3. HANDLE MISSING VALUES
# ============================================================

# Replace impossible zero values with NaN
zero_columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

for column in zero_columns:
    df[column] = df[column].replace(0, np.nan)

print("\nMissing Values After Replacing Zeros:")
print(df.isnull().sum())

# Fill missing numerical values with median
for column in zero_columns:
    df[column] = df[column].fillna(
        df[column].median()
    )

print("\nMissing values handled successfully!")


# ============================================================
# 4. CREATE DIABETES SEVERITY
# ============================================================

# Create 3 severity levels using Glucose
#
# 0 = Low
# 1 = Medium
# 2 = High

df["Severity"] = pd.cut(
    df["Glucose"],
    bins=[-np.inf, 100, 140, np.inf],
    labels=[0, 1, 2]
)

# Convert to integer
df["Severity"] = df["Severity"].astype(int)

print("\nDiabetes Severity Distribution:")
print(df["Severity"].value_counts().sort_index())


# ============================================================
# 5. VISUALIZE SEVERITY
# ============================================================

plt.figure(figsize=(7, 5))

sns.countplot(
    x="Severity",
    data=df
)

plt.title("Diabetes Severity Distribution")
plt.xlabel("Severity")
plt.ylabel("Count")

plt.show()


# ============================================================
# 6. SELECT FEATURES AND TARGET
# ============================================================

features = [
    "Pregnancies",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age"
]

X = df[features]

y = df["Severity"]

print("\nFeatures:")
print(features)

print("\nTarget:")
print("Severity")


# ============================================================
# 7. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)


# ============================================================
# 8. FEATURE SCALING
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)

print("\nFeature Scaling Completed!")


# ============================================================
# 9. MULTINOMIAL LOGISTIC REGRESSION
# ============================================================

model = LogisticRegression(
    multi_class="multinomial",
    max_iter=1000
)

model.fit(
    X_train_scaled,
    y_train
)

print("\nMultinomial Logistic Regression Model Trained!")


# ============================================================
# 10. MAKE PREDICTIONS
# ============================================================

y_pred = model.predict(
    X_test_scaled
)


# ============================================================
# 11. MODEL ACCURACY
# ============================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\n==============================")
print("MODEL ACCURACY")
print("==============================")

print("Accuracy:", accuracy)


# ============================================================
# 12. CLASSIFICATION REPORT
# ============================================================

print("\n==============================")
print("CLASSIFICATION REPORT")
print("==============================")

print(
    classification_report(
        y_test,
        y_pred
    )
)


# ============================================================
# 13. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\n==============================")
print("CONFUSION MATRIX")
print("==============================")

print(cm)


# ============================================================
# 14. CONFUSION MATRIX VISUALIZATION
# ============================================================

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Low",
        "Medium",
        "High"
    ]
)

disp.plot()

plt.title(
    "Diabetes Severity - Confusion Matrix"
)

plt.show()


# ============================================================
# 15. ACTUAL VS PREDICTED
# ============================================================

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print("\n==============================")
print("ACTUAL VS PREDICTED")
print("==============================")

print(comparison.head(20))


# ============================================================
# 16. MODEL COEFFICIENTS
# ============================================================

coefficients = pd.DataFrame(
    model.coef_,
    columns=features,
    index=[
        "Low",
        "Medium",
        "High"
    ]
)

print("\n==============================")
print("MODEL COEFFICIENTS")
print("==============================")

print(coefficients)


# ============================================================
# 17. COEFFICIENT VISUALIZATION
# ============================================================

coefficients.T.plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title(
    "Multinomial Logistic Regression Coefficients"
)

plt.xlabel("Features")
plt.ylabel("Coefficient")

plt.xticks(rotation=45)

plt.show()


# ============================================================
# 18. FINAL RESULT
# ============================================================

print("\n======================================")
print("DIABETES MULTINOMIAL LOGISTIC REGRESSION")
print("PROJECT COMPLETED")
print("======================================")

print("\nFinal Accuracy:")
print(accuracy)