# -*- coding: utf-8 -*-
"""Skill prgrm - 11 - Wine quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sIbTW_9GeEUtNXXyYCQdYLe918E1Aii9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier, plot_tree

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# ------------------------------------------------------------
# 1. LOAD WINE QUALITY DATASET
# ------------------------------------------------------------

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"

df = pd.read_csv(url, sep=";")

print("First 5 rows:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

# ------------------------------------------------------------
# 2. CHECK MISSING VALUES
# ------------------------------------------------------------

print("\nMissing Values:")
print(df.isnull().sum())

# ------------------------------------------------------------
# 3. CREATE CLASSIFICATION TARGET
# ------------------------------------------------------------

# Quality <= 5 = 0 (Low Quality)
# Quality > 5 = 1 (High Quality)

df["quality_label"] = (df["quality"] > 5).astype(int)

print("\nQuality Class Distribution:")
print(df["quality_label"].value_counts())

# ------------------------------------------------------------
# 4. CREATE X AND Y
# ------------------------------------------------------------

X = df.drop(["quality", "quality_label"], axis=1)

y = df["quality_label"]

# ------------------------------------------------------------
# 5. TRAIN TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

# ============================================================
# PART A - DECISION TREE
# ============================================================

dt_model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,
    random_state=42
)

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

print("\n================ DECISION TREE ================")

print("Accuracy:",
      accuracy_score(y_test, dt_pred))

print("\nClassification Report:")
print(classification_report(y_test, dt_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, dt_pred))

# ------------------------------------------------------------
# DECISION TREE VISUALIZATION
# ------------------------------------------------------------

plt.figure(figsize=(20, 10))

plot_tree(
    dt_model,
    feature_names=X.columns,
    class_names=["Low Quality", "High Quality"],
    filled=True,
    rounded=True
)

plt.title("Wine Quality Decision Tree")

plt.show()

# ------------------------------------------------------------
# DECISION TREE FEATURE IMPORTANCE
# ------------------------------------------------------------

dt_importance = pd.Series(
    dt_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print("\nDecision Tree Feature Importance:")
print(dt_importance)

plt.figure(figsize=(10, 6))

dt_importance.plot(kind="bar")

plt.title("Decision Tree Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance")
plt.xticks(rotation=45)

plt.show()

# ============================================================
# PART B - RANDOM FOREST
# ============================================================

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=8,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("\n================ RANDOM FOREST ================")

print("Accuracy:",
      accuracy_score(y_test, rf_pred))

print("\nClassification Report:")
print(classification_report(y_test, rf_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

# ------------------------------------------------------------
# RANDOM FOREST FEATURE IMPORTANCE
# ------------------------------------------------------------

rf_importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print("\nRandom Forest Feature Importance:")
print(rf_importance)

plt.figure(figsize=(10, 6))

rf_importance.plot(kind="bar")

plt.title("Random Forest Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance")
plt.xticks(rotation=45)

plt.show()

# ============================================================
# PART C - MODEL COMPARISON
# ============================================================

dt_accuracy = accuracy_score(y_test, dt_pred)
rf_accuracy = accuracy_score(y_test, rf_pred)

comparison = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Random Forest"
    ],
    "Accuracy": [
        dt_accuracy,
        rf_accuracy
    ]
})

print("\n================ MODEL COMPARISON ================")

print(comparison)

plt.figure(figsize=(8, 5))

plt.bar(
    comparison["Model"],
    comparison["Accuracy"]
)

plt.ylim(0, 1)

plt.title("Wine Quality Model Comparison")
plt.ylabel("Accuracy")

plt.show()