# -*- coding: utf-8 -*-
"""Skill prgrm -2 - Titanic Survival.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGWyyb4UnUQwf_Sx4-8Hr4YNAs6mlMsz
"""

# ============================================================
# TITANIC SURVIVAL — PREPROCESSING PIPELINE
# ============================================================

import pandas as pd
import numpy as np

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# ============================================================
# 1. UPLOAD CSV
# ============================================================

uploaded = files.upload()

filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)

print("CSV loaded successfully!")
print("Original shape:", df.shape)

# ============================================================
# 2. DISPLAY ORIGINAL DATASET
# ============================================================

print("\n===== ORIGINAL DATASET =====")
display(df.head(10))

# ============================================================
# 3. CHECK MISSING VALUES
# ============================================================

print("\n===== MISSING VALUES =====")
print(df.isnull().sum())

# ============================================================
# 4. SELECT FEATURES AND TARGET
# ============================================================

features = [
    "pclass",
    "sex",
    "age",
    "sibsp",
    "parch",
    "fare",
    "embarked"
]

target = "survived"

X = df[features]
y = df[target]

# ============================================================
# 5. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining shape:", X_train.shape)
print("Testing shape:", X_test.shape)

# ============================================================
# 6. NUMERICAL AND CATEGORICAL FEATURES
# ============================================================

numerical_features = [
    "pclass",
    "age",
    "sibsp",
    "parch",
    "fare"
]

categorical_features = [
    "sex",
    "embarked"
]

# ============================================================
# 7. NUMERICAL PIPELINE
# ============================================================

numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# ============================================================
# 8. CATEGORICAL PIPELINE
# ============================================================

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False
    ))
])

# ============================================================
# 9. COMBINE PIPELINES
# ============================================================

preprocessor = ColumnTransformer([
    ("numerical", numerical_pipeline, numerical_features),
    ("categorical", categorical_pipeline, categorical_features)
])

# ============================================================
# 10. PREPROCESS DATA
# ============================================================

X_processed = preprocessor.fit_transform(X)

# ============================================================
# 11. GET PROCESSED FEATURE NAMES
# ============================================================

feature_names = preprocessor.get_feature_names_out()

# ============================================================
# 12. CREATE CLEANED DATASET
# ============================================================

cleaned_df = pd.DataFrame(
    X_processed,
    columns=feature_names
)

# Add target column
cleaned_df["survived"] = y.values

# ============================================================
# 13. DISPLAY CLEANED DATASET
# ============================================================

print("\n===== CLEANED DATASET =====")

display(cleaned_df.head(10))

# ============================================================
# 14. CLEANED DATASET INFORMATION
# ============================================================

print("\nCleaned dataset shape:", cleaned_df.shape)

print("\n===== MISSING VALUES AFTER PREPROCESSING =====")
print(cleaned_df.isnull().sum())

print("\n===== CLEANED DATA TYPES =====")
print(cleaned_df.dtypes)