# -*- coding: utf-8 -*-
"""skill prgrm 8-Heart disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyWT5JOeadDQ0RagEOf218UxbSFrBIcP
"""

# Install required libraries
!pip -q install ucimlrepo

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from ucimlrepo import fetch_ucirepo

# ------------------------------------------------------------
# 1. LOAD DATASET
# ------------------------------------------------------------

heart_disease = fetch_ucirepo(id=45)

X = heart_disease.data.features
y = heart_disease.data.targets

# Convert target to binary:
# 0 = No Disease
# 1 = Disease
y = y.iloc[:, 0]
y = (y > 0).astype(int)

print("Dataset shape:", X.shape)
print("\nFeatures:")
print(X.columns)

print("\nTarget distribution:")
print(y.value_counts())

# ------------------------------------------------------------
# 2. HANDLE MISSING VALUES
# ------------------------------------------------------------

X = X.copy()

for column in X.columns:
    X[column] = pd.to_numeric(X[column], errors='coerce')

X = X.fillna(X.median())

# ------------------------------------------------------------
# 3. TRAIN TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

# ------------------------------------------------------------
# 4. CREATE DECISION TREE
# ------------------------------------------------------------

model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=4,
    random_state=42
)

model.fit(X_train, y_train)

# ------------------------------------------------------------
# 5. PREDICTION
# ------------------------------------------------------------

y_pred = model.predict(X_test)

# ------------------------------------------------------------
# 6. EVALUATION
# ------------------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ------------------------------------------------------------
# 7. VISUALIZE DECISION TREE
# ------------------------------------------------------------

plt.figure(figsize=(20, 10))

plot_tree(
    model,
    feature_names=X.columns,
    class_names=["No Disease", "Disease"],
    filled=True,
    rounded=True
)

plt.title("Heart Disease Decision Tree")
plt.show()

# ------------------------------------------------------------
# 8. FEATURE IMPORTANCE
# ------------------------------------------------------------

importance = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print("\nFeature Importance:")
print(importance)

plt.figure(figsize=(10, 6))
importance.plot(kind="bar")
plt.title("Decision Tree Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance")
plt.xticks(rotation=45)
plt.show()