# -*- coding: utf-8 -*-
"""Skill prgrm9 - Hear disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11K5xza7o0vKYojsEROHbimBfw5VLPCvM
"""

!pip -q install ucimlrepo

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from ucimlrepo import fetch_ucirepo

# ------------------------------------------------------------
# 1. LOAD DATASET
# ------------------------------------------------------------

heart_disease = fetch_ucirepo(id=45)

X = heart_disease.data.features
y = heart_disease.data.targets

# Convert target into binary
y = y.iloc[:, 0]
y = (y > 0).astype(int)

# ------------------------------------------------------------
# 2. CLEAN DATA
# ------------------------------------------------------------

X = X.copy()

for column in X.columns:
    X[column] = pd.to_numeric(X[column], errors="coerce")

X = X.fillna(X.median())

print("Dataset shape:", X.shape)

# ------------------------------------------------------------
# 3. TRAIN TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# ------------------------------------------------------------
# 4. RANDOM FOREST MODEL
# ------------------------------------------------------------

rf_model = RandomForestClassifier(
    n_estimators=100,
    criterion="gini",
    max_depth=6,
    random_state=42
)

rf_model.fit(X_train, y_train)

# ------------------------------------------------------------
# 5. PREDICTION
# ------------------------------------------------------------

y_pred = rf_model.predict(X_test)

# ------------------------------------------------------------
# 6. EVALUATION
# ------------------------------------------------------------

print("Random Forest Accuracy:",
      accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ------------------------------------------------------------
# 7. FEATURE IMPORTANCE
# ------------------------------------------------------------

importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print("\nFeature Importance:")
print(importance)

plt.figure(figsize=(10, 6))

importance.plot(kind="bar")

plt.title("Random Forest Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance")
plt.xticks(rotation=45)

plt.show()

# ------------------------------------------------------------
# 8. SINGLE PATIENT PREDICTION EXAMPLE
# ------------------------------------------------------------

sample = X_test.iloc[[0]]

prediction = rf_model.predict(sample)

if prediction[0] == 1:
    print("\nPrediction: Heart Disease")
else:
    print("\nPrediction: No Heart Disease")

print("\nProbability:")
print(rf_model.predict_proba(sample))