# -*- coding: utf-8 -*-
"""Skill prgrm-10-Heart Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pA43eg-3rOvMUSgndEko8xET3CdUnAc
"""

!pip -q install ucimlrepo xgboost lightgbm shap

# ------------------------------------------------------------
# IMPORT LIBRARIES
# ------------------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

import shap

from ucimlrepo import fetch_ucirepo

# ------------------------------------------------------------
# 1. LOAD HEART DISEASE DATASET
# ------------------------------------------------------------

heart_disease = fetch_ucirepo(id=45)

X = heart_disease.data.features
y = heart_disease.data.targets

# Convert target into binary
y = y.iloc[:, 0]
y = (y > 0).astype(int)

# ------------------------------------------------------------
# 2. CLEAN DATA
# ------------------------------------------------------------

X = X.copy()

for column in X.columns:
    X[column] = pd.to_numeric(X[column], errors="coerce")

X = X.fillna(X.median())

print("Dataset Shape:", X.shape)

# ------------------------------------------------------------
# 3. TRAIN TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# ============================================================
# PART A - XGBOOST
# ============================================================

xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)

print("\n================ XGBOOST ================")

print("Accuracy:",
      accuracy_score(y_test, xgb_pred))

print("\nClassification Report:")
print(classification_report(y_test, xgb_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_pred))

# ============================================================
# PART B - LIGHTGBM
# ============================================================

lgb_model = LGBMClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=4,
    num_leaves=15,
    random_state=42,
    verbosity=-1
)

lgb_model.fit(X_train, y_train)

lgb_pred = lgb_model.predict(X_test)

print("\n================ LIGHTGBM ================")

print("Accuracy:",
      accuracy_score(y_test, lgb_pred))

print("\nClassification Report:")
print(classification_report(y_test, lgb_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, lgb_pred))

# ============================================================
# PART C - COMPARE MODELS
# ============================================================

xgb_accuracy = accuracy_score(y_test, xgb_pred)
lgb_accuracy = accuracy_score(y_test, lgb_pred)

comparison = pd.DataFrame({
    "Model": ["XGBoost", "LightGBM"],
    "Accuracy": [xgb_accuracy, lgb_accuracy]
})

print("\nModel Comparison:")
print(comparison)

plt.figure(figsize=(7, 5))

plt.bar(
    comparison["Model"],
    comparison["Accuracy"]
)

plt.ylim(0, 1)

plt.title("XGBoost vs LightGBM")
plt.ylabel("Accuracy")

plt.show()

# ============================================================
# PART D - SHAP FOR XGBOOST
# ============================================================

print("\n================ SHAP XGBOOST ================")

explainer_xgb = shap.TreeExplainer(xgb_model)

shap_values_xgb = explainer_xgb.shap_values(X_test)

# SHAP summary plot
shap.summary_plot(
    shap_values_xgb,
    X_test,
    feature_names=X_test.columns
)

# SHAP bar plot
shap.summary_plot(
    shap_values_xgb,
    X_test,
    feature_names=X_test.columns,
    plot_type="bar"
)

# ============================================================
# PART E - SHAP FOR LIGHTGBM
# ============================================================

print("\n================ SHAP LIGHTGBM ================")

explainer_lgb = shap.TreeExplainer(lgb_model)

shap_values_lgb = explainer_lgb.shap_values(X_test)

# Handle different SHAP output formats
if isinstance(shap_values_lgb, list):
    shap_values_lgb_plot = shap_values_lgb[1]
else:
    shap_values_lgb_plot = shap_values_lgb

shap.summary_plot(
    shap_values_lgb_plot,
    X_test,
    feature_names=X_test.columns
)

shap.summary_plot(
    shap_values_lgb_plot,
    X_test,
    feature_names=X_test.columns,
    plot_type="bar"
)

# ============================================================
# PART F - MOST IMPORTANT FEATURES
# ============================================================

xgb_importance = pd.Series(
    xgb_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print("\nXGBoost Important Features:")
print(xgb_importance)

lgb_importance = pd.Series(
    lgb_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print("\nLightGBM Important Features:")
print(lgb_importance)