# -*- coding: utf-8 -*-
"""titanic linearregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABa8geVhqJp3cFEF-FKzhNNnI8qIeM_t
"""

# ============================================================
# TITANIC SURVIVAL - FULL LOGISTIC REGRESSION PIPELINE
# ============================================================

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

# ============================================================
# 1. LOAD DATASET
# ============================================================

uploaded = files.upload()

filename = next(iter(uploaded))

df = pd.read_csv(filename)

print("Dataset loaded successfully!")

print("\nFirst 5 rows:")
print(df.head())


# ============================================================
# 2. BASIC INFORMATION
# ============================================================

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())


# ============================================================
# 3. EXPLORATORY DATA ANALYSIS
# ============================================================

# Survival distribution

plt.figure(figsize=(7, 5))

sns.countplot(
    x="Survived",
    data=df
)

plt.title("Titanic Survival Distribution")
plt.xlabel("Survived")
plt.ylabel("Count")

plt.show()


# Survival by gender

plt.figure(figsize=(7, 5))

sns.countplot(
    x="Sex",
    hue="Survived",
    data=df
)

plt.title("Survival by Gender")
plt.xlabel("Gender")
plt.ylabel("Count")

plt.show()


# Survival by passenger class

plt.figure(figsize=(7, 5))

sns.countplot(
    x="Pclass",
    hue="Survived",
    data=df
)

plt.title("Survival by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Count")

plt.show()


# Age distribution

plt.figure(figsize=(8, 5))

sns.histplot(
    df["Age"].dropna(),
    bins=30,
    kde=True
)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")

plt.show()


# ============================================================
# 4. SELECT FEATURES AND TARGET
# ============================================================

features = [
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked"
]

X = df[features]

y = df["Survived"]

print("\nFeatures:")
print(features)

print("\nTarget:")
print("Survived")


# ============================================================
# 5. DEFINE NUMERICAL AND CATEGORICAL FEATURES
# ============================================================

numeric_features = [
    "Pclass",
    "Age",
    "SibSp",
    "Parch",
    "Fare"
]

categorical_features = [
    "Sex",
    "Embarked"
]


# ============================================================
# 6. NUMERICAL PREPROCESSING PIPELINE
# ============================================================

numeric_pipeline = Pipeline([

    ("imputer", SimpleImputer(
        strategy="median"
    )),

    ("scaler", StandardScaler())
])


# ============================================================
# 7. CATEGORICAL PREPROCESSING PIPELINE
# ============================================================

categorical_pipeline = Pipeline([

    ("imputer", SimpleImputer(
        strategy="most_frequent"
    )),

    ("encoder", OneHotEncoder(
        handle_unknown="ignore"
    ))
])


# ============================================================
# 8. COMBINE PREPROCESSING
# ============================================================

preprocessor = ColumnTransformer([

    ("numeric",
     numeric_pipeline,
     numeric_features),

    ("categorical",
     categorical_pipeline,
     categorical_features)
])


# ============================================================
# 9. CREATE COMPLETE LOGISTIC REGRESSION PIPELINE
# ============================================================

model = Pipeline([

    ("preprocessor", preprocessor),

    ("classifier",
     LogisticRegression(
         max_iter=1000
     ))
])


# ============================================================
# 10. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)


# ============================================================
# 11. TRAIN THE MODEL
# ============================================================

model.fit(
    X_train,
    y_train
)

print("\nLogistic Regression Model Trained Successfully!")


# ============================================================
# 12. MAKE PREDICTIONS
# ============================================================

y_pred = model.predict(
    X_test
)


# ============================================================
# 13. MODEL ACCURACY
# ============================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\n==============================")
print("MODEL ACCURACY")
print("==============================")

print("Accuracy:", accuracy)


# ============================================================
# 14. CLASSIFICATION REPORT
# ============================================================

print("\n==============================")
print("CLASSIFICATION REPORT")
print("==============================")

print(
    classification_report(
        y_test,
        y_pred
    )
)


# ============================================================
# 15. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\n==============================")
print("CONFUSION MATRIX")
print("==============================")

print(cm)


# ============================================================
# 16. CONFUSION MATRIX VISUALIZATION
# ============================================================

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Not Survived",
        "Survived"
    ]
)

disp.plot()

plt.title(
    "Titanic Logistic Regression - Confusion Matrix"
)

plt.show()


# ============================================================
# 17. SAMPLE PREDICTIONS
# ============================================================

sample = X_test.head(10)

sample_predictions = model.predict(
    sample
)

print("\n==============================")
print("SAMPLE PREDICTIONS")
print("==============================")

print(
    pd.DataFrame({
        "Actual": y_test.head(10).values,
        "Predicted": sample_predictions
    })
)


# ============================================================
# 18. FINAL RESULT
# ============================================================

print("\n======================================")
print("TITANIC LOGISTIC REGRESSION COMPLETED")
print("======================================")

print("\nFinal Accuracy:")
print(accuracy)